codecov:
  require_ci_to_pass: true

coverage:
  range: "70...100"

  status:
    project:
      default:
        # Fail the status if coverage drops by >= 0.1%
        threshold: 0.1
    patch:
      default:
        target: 80%
        # Only post a patch status to pull requests
        only_pulls: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no