= robotframework-gradle-plugin
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]

Gradle plugin for using the https://robotframework.org/[Robot Framework].
This project is inspired by the https://github.com/robotframework/MavenPlugin[robotframework maven plugin].
Its goal is to enable you to use the Robot Framework in a gradle project without the need to install anything extra
(e.g. Robotframework, Jython, etc.).

[IMPORTANT]
This plugin is just a convenient wrapper for the https://github.com/robotframework/robotframework/blob/master/INSTALL.rst#standalone-jar-distribution[robotframework standalone-jar-distribution]! Therefore, it primarily addresses RF libraries written in java.

[cols="1,~", frame=none, grid=none]
|===
|General
|image:https://img.shields.io/github/license/qualersoft/robotframework-gradle-plugin[link=https://github.com/qualersoft/robotframework-gradle-plugin/blob/main/LICENSE]
image:https://app.fossa.com/api/projects/git%2Bgithub.com%2Fqualersoft%2Frobot-gradle-plugin.svg?type=shield[link=https://app.fossa.com/projects/custom%2B17788%2Frobotframework-gradle-plugin/refs/branch/main/]

|Main
|image:https://github.com/qualersoft/robotframework-gradle-plugin/actions/workflows/build.yml/badge.svg?branch=main[title="Build status", link=https://github.com/qualersoft/robotframework-gradle-plugin/blob/main/.github/workflows/build.yml]
image:https://www.codefactor.io/repository/github/qualersoft/robotframework-gradle-plugin/badge/main?s=2996b4322bfcdca3d8e6250191d67a1410cf3a16[title="Code quality", link=https://www.codefactor.io/repository/github/qualersoft/robotframework-gradle-plugin/overview/main]
image:https://codecov.io/gh/qualersoft/robotframework-gradle-plugin/branch/main/graph/badge.svg?token=Z5CT2C7LN1[title="Coverage", link=https://codecov.io/gh/qualersoft/robotframework-gradle-plugin]

|Develop
|image:https://github.com/qualersoft/robotframework-gradle-plugin/actions/workflows/build.yml/badge.svg?branch=develop[title="Build status", link=https://github.com/qualersoft/robotframework-gradle-plugin/blob/develop/.github/workflows/build.yml]
image:https://www.codefactor.io/repository/github/qualersoft/robotframework-gradle-plugin/badge/develop?s=2996b4322bfcdca3d8e6250191d67a1410cf3a16[title="Code quality", link=https://www.codefactor.io/repository/github/qualersoft/robotframework-gradle-plugin/overview/develop]
image:https://codecov.io/gh/qualersoft/robotframework-gradle-plugin/branch/develop/graph/badge.svg?token=Z5CT2C7LN1[title="Coverage", link=https://codecov.io/gh/qualersoft/robotframework-gradle-plugin]
|===

== Quickstart
Just add the following lines to you build.gradle(.kts)
[source,kotlin]
----
import de.qualersoft.robotframework.gradleplugin.tasks

plugins {
  id("de.qualersoft.robotframework") version "<latest>"
}

tasks.register<RunRobotTask>("robotTest") {
  sources = fileTree("src/test") {
    include("**/*.robot")
  }
}
----

[NOTE]
Don't forget to replace the version `"<latest>"` with the appropriate version😉

Assuming you have some robot test suite files somewhere under your `src/test` folder, calling

[source,shell]
----
./gradlew robotTest
----
starts the test execution.

For further configuration and examples have a look at the file://./src/funcTest/resources[test resources].

== Available tasks ^(<<package-note,*>>)^
For details see http://robotframework.org/robotframework/#built-in-tools[robot framework tasks]

RunRobotTask:: same as `robot.run` command
LibdocTask:: same as `robot.libdoc` command
TestdocTask:: same as `robot.testdoc` command
RebotTask:: same as `robot.rebot` command
TidyTask:: same as `robot.tidy` command

[[package-note]]
(*) All task implementations are in package `de.qualersoft.robotframework.gradleplugin.tasks`

== Remark on tasks
=== LibdocTask
When using libdoc with more than one file, the target file extension is determined either by the value of the `format` parameter (if not `null`) or by the extension given to the `outputFile` property. This ensures maximum compatibility with older RF versions that do not support the `format` flag. In case `outputFile` will be used, the name itself is ignored. In case `format` is used, its value is directly used! Take care to use a valid value, otherwise it could cause strange errors.